### ISSUE TITLE
GDNative to generate samples faster

### ISSUE THREAD

**Issue by samsface** [tomeyro/godot-sfxr#1]
This plugin is great but it's not productive for me because generating samples is too slow.

I made generating the sample instant more or less using GDNative C++. I can open a pr? Or will just fork into my own addon if you don't feel like complicating it.

https://user-images.githubusercontent.com/4586101/151241681-9b0cf559-1f94-4127-8a6d-259090134e5d.mp4

**Comment by tomeyro** [comment]
You can open a PR :+1: 

I know gdscript was the slow option, but didn't have the time to check/learn how to make it with gdnative :stuck_out_tongue:

**Comment by samsface** [comment]
I've actually changed too much stuff now :sweat_smile: so don't think it could be merged anymore. I'll stick on my fork :+1:
