### ISSUE TITLE
Doesn't work in Godot 4.0.1 stable

### ISSUE THREAD

**Issue by JoshuaWeissTBS** [tomeyro/godot-sfxr#10]
After loading in the addon from the repo and enabling it, correctly creates the Sfxr audio stream node, but using the audio stream node has none of the special properties, it acts like a regular audio node as in the screenshot below.

![image](https://github.com/tomeyro/godot-sfxr/assets/44821795/f741485a-ae91-444a-9777-994c236bcb58)

**Comment by JoshuaWeissTBS** [comment]
Opening the project directly from your repo in godot 4.0.1s doesn't work either.

**Comment by makabeus** [comment]
In script editor: `Search` > `Replace in Files...`
  `Find`: `property: String`
  `Replace`: `property: StringName`

Should be `10 matches in 4 files`. `Replace All`. `Save All`.

Works in Godot 4.1

Credit goes to @fskfskfsk https://github.com/tomeyro/godot-sfxr/issues/9#issuecomment-1435782133 :)

PS. Don't forget to disable/enable in Project Settings > Plugins after saving.

**Comment by tomeyro** [comment]
It was such a small change but I really didn't have the time to look into it. Thanks @makabeus :) The fix is on 4.x
