### ISSUE TITLE
Save audio for later use

### ISSUE THREAD

**Issue by MrEliptik** [tomeyro/godot-sfxr#2]
Do you think it would be possible to save the audio generate as a file or a resource to be used later? It could be super useful and interesting for performances reasons for example.

**Comment by tomeyro** [comment]
I tried that but the files were ~250kb and I think that is too much. I guess I could add the option and let people decide if they want to use it.

**Comment by MrEliptik** [comment]
Yeah adding the option would be awesome!

**Comment by samsface** [comment]
I added this option in my fork, works nicely. I store the buffer as an export var so Godot saves it along with the packed scene. It's great for runtime performance. I don't think size maters much here, it's same as the equivalent WAV file.

https://user-images.githubusercontent.com/4586101/152706679-85844ec6-cc54-41c5-aafc-bf6f381fe951.mp4

**Comment by tomeyro** [comment]
So I just a pushed a big change and now the generator creates an ``AudioStreamSample`` resource with the audio data. You can now see the resource on the inspector and save it to use it anywhere else you like.

You can read more [here](https://tomeyro.itch.io/godot-sfxr/devlog/344661/godotsfxr-post-jam-version).
