### ISSUE TITLE
How to call `_build_buffer` before a node has been generated?

### ISSUE THREAD

**Issue by tavurth** [tomeyro/godot-sfxr#3]
Awesome project 🤗 I've been waiting for something like this for a long time.

Since in Godot everything is a node, it would be nice to spawn an instance of a node, but have it buffer the sound when it's loaded instead of at the instance time.

Any idea of how to go about that?

**Comment by tavurth** [comment]
Temporary fix in my PR but it would be nice to have a bit more robust system for buffering on load if you can think of anything.

**Comment by tomeyro** [comment]
Hi, @tavurth 

I just pushed a new version with no longer uses the AudioStreamGenerator and now uses the AudioStreamSample, which can be generated once and reused, so you don't have to worry anymore about using the _build_buffer function.

You can read more about the new version [here](https://tomeyro.itch.io/godot-sfxr/devlog/344661/godotsfxr-post-jam-version).
