### ISSUE TITLE
Port to resource

### ISSUE THREAD

**Issue by ettiSurreal** [tomeyro/godot-sfxr#8]
Having separate nodes seems a bit redundant, wouldn't it be better for it to be a AudioStream resource, for less clutter and compatibility with other custom stream players?

**Comment by tomeyro** [comment]
Hello, @ettiSurreal ! Now you can use the `SfxrAudioStream` Resource with any `AudioStreamPlayer` you want :)

The custom `SfxrStreamPlayer*` still exist for the users that prefer it that way.
