### ISSUE TITLE
Not working in Godot 4 beta 10

### ISSUE THREAD

**Issue by cessar1** [tomeyro/godot-sfxr#9]
Hi im using  this version [https://godotengine.org/article/dev-snapshot-godot-4-0-beta-10](url) and I-m getting this error.
Parser Error: The function signature doesn't match the parent. Parent signature is "property_can_revert(StringName) -> bool".

![imagen](https://user-images.githubusercontent.com/10481786/211676797-b3c2d9e8-8d04-4d95-b2c9-730b2ce54309.png)

**Comment by fskfskfsk** [comment]
You have to change those two lines to:

    func property_can_revert(property: StringName):

and then it will work.

The base class it inherits from was changed in Godot 4.

**Comment by cessar1** [comment]
thank you!

**Comment by tomeyro** [comment]
Thanks to @fskfskfsk !! 4.x is now fixed
